# Generated by Django 3.2.4 on 2021-06-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petshop", "0002_alter_customer_identity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="identity",
            new_name="document",
        ),
    ]
