# Generated by Django 3.2.4 on 2021-06-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petshop", "0004_pet_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_in_school",
                    models.CharField(
                        choices=[
                            ("FR", "Freshman"),
                            ("SO", "Sophomore"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("GR", "Graduate"),
                        ],
                        default="FR",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
