# Generated by Django 3.2.4 on 2021-06-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petshop", "0005_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.AlterField(
            model_name="pet",
            name="size",
            field=models.CharField(
                choices=[
                    ("UNSELECTED", "Não Selecionado"),
                    ("PUPPY", "Filhote"),
                    ("SMALL", "Pequeno"),
                    ("MEDIUM", "Médio"),
                    ("LARGE", "Grande"),
                    ("GIANT", "Gigante"),
                ],
                max_length=10,
            ),
        ),
    ]
