# Generated by Django 3.2.4 on 2021-06-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petshop", "0006_auto_20210623_2247"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="size",
            field=models.CharField(
                choices=[
                    ("PUPPY", "Filhote"),
                    ("SMALL", "Pequeno"),
                    ("MEDIUM", "Médio"),
                    ("LARGE", "Grande"),
                    ("GIANT", "Gigante"),
                ],
                max_length=6,
            ),
        ),
    ]
