# Generated by Django 3.2.4 on 2021-06-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0009_alter_customer_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.CharField(max_length=11),
        ),
    ]
